In [ ]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
filename = next(iter(uploaded))
df= pd.read_csv(filename)
print("Loaded successfully! ")
print("File:",filename)
print("shape:",df.shape)
display(df.head())

Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Loaded successfully!
File: olist_customers_dataset.csv
shape: (99441, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print("/nColumn names:")
print(df.columns.tolist())

/nColumn names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [ ]:
print("/nData types:")
print(df.dtypes)

/nData types:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [ ]:
print("/nMissing values:")
print(df.isna().sum())

/nMissing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
print("/nFirst 5 rows:")
display(df.head())

/nFirst 5 rows:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
df.columns=(df.columns.str.strip().str.lower().str.replace(" ","_"))

In [ ]:
text_columns = ["customer_id","customer_unique_id","customer_city","customer_state"]

In [ ]:
for col in text_columns:
  df[col]=df[col].astype("string").str.strip()

In [ ]:
df["customer_city"]=(df["customer_city"].str.lower().str.title())

In [ ]:
df["customer_state"]=(df["customer_state"].str.upper().str.strip())

In [ ]:
print("Column names after standardization:")
print(df.columns.tolist())

Column names after standardization:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [ ]:
print("/n Sample cleaned text:")
display(df[["customer_id","customer_unique_id","customer_city","customer_state"]].head())

/n Sample cleaned text:

,customer_id,customer_unique_id,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,Franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,Sao Bernardo Do Campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,Sao Paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,Mogi Das Cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,Campinas,SP

In [ ]:
customer_id_duplicates = df["customer_id"].duplicated().sum()
print(f"Duplicated_customer_id values:{customer_id_duplicates:,}")

Duplicated_customer_id values:0

In [ ]:
if customer_id_duplicates == 0:
    print("PASS: customer_id is unique.")
else:
    print("WARNING: customer_id contains duplicates.")
    print("\nDuplicate customer_id records:")
    display(
        df[df["customer_id"].duplicated(keep=False)]
        .sort_values("customer_id")
    )

PASS: customer_id is unique.

In [ ]:
customer_frequency = (df.groupby("customer_unique_id").size().reset_index(name="record_count"))
repeat_customers = customer_frequency[customer_frequency["record_count"]>1]
unique_customers = customer_frequency.shape[0]
print(f"/nUnique_customer_id values:{unique_customers:,}")
print(f"Repeat customer_unique_id values:{unique_customers:,}")
print("/nTop repeat customer IDs:")
display(repeat_customers.sort_values("record_count",ascending=False).head(10))

/nUnique_customer_id values:96,096
Repeat customer_unique_id values:96,096
/nTop repeat customer IDs:

                     customer_unique_id  record_count
52973  8d50f5eadf50201ccdcedfb9e2ac8455            17
23472  3e43e6105506432c953e165fb2acf44c             9
37797  6469f99c1f9dfae7733b25662e7f1782             7
76082  ca77025e7201e3b30c44b472ff346268             7
10354  1b6c7548a2a1f9037c1fd3ddfed95f33             7
83540  de34b16117594161a6a89c50b289d35a             6
90451  f0e310a6839dce9de1638e0fe5ab282a             6
82883  dc813062e0fc23409cd255f7f53c7074             6
7175   12f5d6e1cbf93dafd9dcc19095df0b3d             6
37585  63cfc61cee11cbe306bff5857d00bfe4             6

In [ ]:
missing_values = df.isna().sum()
duplicate_rows = df.duplicated().sum()

print("Missing values by column:")
print(missing_values)

print(f"\nDuplicate complete rows: {duplicate_rows:,}")

if missing_values.sum() == 0:
    print("PASS: No missing values.")
else:
    print("WARNING: Missing values detected.")

if duplicate_rows == 0:
    print("PASS: No duplicate complete rows.")
else:
    print("WARNING: Duplicate complete rows detected.")

Missing values by column:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate complete rows: 0
PASS: No missing values.
PASS: No duplicate complete rows.

In [ ]:
df["customer_zip_code_prefix"] = pd.to_numeric(df["customer_zip_code_prefix"],errors="coerce").astype("Int64")
df["customer_zip_code_prefix"] = (
    df["customer_zip_code_prefix"]
    .astype("string")
    .str.zfill(5)
)
print("ZIP code prefix sample:")
display(
    df["customer_zip_code_prefix"].head(10)
)

ZIP code prefix sample:

0    14409
1    09790
2    01151
3    08775
4    13056
5    89254
6    04534
7    35182
8    81560
9    30575
Name: customer_zip_code_prefix, dtype: string

In [ ]:
df["customer_id"] = df["customer_id"].astype("string")
df["customer_unique_id"] = df["customer_unique_id"].astype("string")
df["customer_city"] = df["customer_city"].astype("string")
df["customer_state"] = df["customer_state"].astype("string")
df["customer_zip_code_prefix"] = (df["customer_zip_code_prefix"].astype("string"))
print("Final data types:")
print(df.dtypes)

Final data types:
customer_id                 string[python]
customer_unique_id          string[python]
customer_zip_code_prefix    string[python]
customer_city               string[python]
customer_state              string[python]
dtype: object

In [ ]:
assert len(df) == 99_441, (f"Unexpected row count: {len(df):,}")
assert len(df.columns)==5, (f"Unexpected column count: {len(df.columns)}")
expected_columns = [
    "customer_id",
    "customer_unique_id",
    "customer_zip_code_prefix",
    "customer_city",
    "customer_state"]
assert df.columns.tolist()==expected_columns,("Column names/order do not match expected structure.")
assert df["customer_id"].is_unique,("Customer id contains duplicate values")
assert df.isna().sum().sum()==0,("Missing values detected")
assert not df.duplicated().any(),("Duplicate complete rows detected.")
assert df["customer_zip_code_prefix"].str.fullmatch(r"\d{5}").all(), ("ZIP code prefix formatting error detected.")
assert df["customer_state"].str.fullmatch(r"[A-Z]{2}").all(), ("Invalid customer_state value detected.")
print("==========================================")
print("ALL SANITY CHECKS PASSED")
print("==========================================")

==========================================
ALL SANITY CHECKS PASSED
==========================================

In [5]:
OUTPUT_FILE = "olist_customers_cleaned.csv"
df.to_csv(OUTPUT_FILE, index=False)
print(f"Clean dataset exported successfully:")
print(OUTPUT_FILE)

Clean dataset exported successfully:
olist_customers_cleaned.csv

In [6]:
df_check = pd.read_csv(OUTPUT_FILE,dtype=
 {"customer_id": "string",
        "customer_unique_id": "string",
        "customer_zip_code_prefix": "string",
        "customer_city": "string",
        "customer_state": "string"})
print("\nFINAL EXPORT VERIFICATION")
print("-------------------------")
print(f"Rows: {df_check.shape[0]:,}")
print(f"Columns: {df_check.shape[1]:,}")
print(f"Missing values: {df_check.isna().sum().sum():,}")
print(f"Duplicate customer_id: {df_check['customer_id'].duplicated().sum():,}")

print("\nFinal dataset preview:")
display(df_check.head())

print("\nPRJ-002 CUSTOMER CLEANING COMPLETE.")

FINAL EXPORT VERIFICATION
-------------------------
Rows: 99,441
Columns: 5
Missing values: 0
Duplicate customer_id: 0

Final dataset preview:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

PRJ-002 CUSTOMER CLEANING COMPLETE.

In [2]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_csv("olist_customers_dataset.csv")

print("Loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Saving olist_customers_dataset.csv to olist_customers_dataset.csv
Loaded successfully!
Shape: (99441, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
import os

print(os.path.exists("olist_customers_cleaned.csv"))

True

In [8]:
from google.colab import files

files.download("olist_customers_cleaned.csv")